### ISSUE TITLE
Add more feature

### ISSUE THREAD

**Issue by tegarimansyah** [tegarimansyah/malas-cli#2]
* [x] SSH local tunneling
* [x] Docker build in remote server
* [x] Run from bash script

**Comment by sleepy0owl** [comment]
I want to work on "run from bash script", can you describe this issue

**Comment by tegarimansyah** [comment]
Hello @souravmondal13 , Sorry but it's already implemented here https://github.com/tegarimansyah/malas-cli/blob/main/malas-cli/malas_config/plugins/tegarimansyah/run_in_remote.py#L36

Thanks for your interest
